project: scprint_scale
seed_everything: 42
ckpt_path: null
set_float32_matmul_precision: True
wandblog: all
log_freq: 200
log_graph: True
trainer:
  precision: 16-mixed
  # profiler: simple
  gradient_clip_val: 100
  log_every_n_steps: 100
  limit_train_batches: 7000
  limit_val_batches: 2000
  limit_test_batches: 1 # we don't perform tests this way
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  max_time:
    hours: 71
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: ${project}
        save_dir: data/log/
        offline: True
  callbacks:
    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.03
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: 20
        save_last: True

    #- class_path: lightning.pytorch.callbacks.LearningRateFinder
    #init_args:
    #  mode: exponential
  #plugins:
  #  - class_path: lightning.pytorch.plugins.environments.SLURMEnvironment
  #    requeue_signal: signal.SIGHUP
model:
  dropout: 0.1
  transformer: flash
  mvc_decoder: inner product
  residual_in_fp32: True
  num_heads_kv: null
  fused_dropout_add_ln: False
  prenorm: True
  fused_mlp: False
  fused_bias_fc: False
  drop_path_rate: 0
  freeze_embeddings: True
  pred_embedding:
    - cell_type_ontology_term_id
    - disease_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
data:
  organisms:
    - NCBITaxon:9606
    - NCBITaxon:10090
  gene_position_tolerance: 10_000
  gene_embeddings: ./data/main/gene_embeddings.parquet
  collection_name: all no zhang13M #preprocessed dataset
  how: random expr
  max_len: 2200
  weight_scaler: 50
  do_gene_pos: ./data/main/biomart_pos.parquet
  add_zero_genes: 0
  train_oversampling_per_epoch: 0.3
  validation_split: 0.02
  test_split: 0.02
  batch_size: 64
  num_workers: 12
  # TODO: drop tissue & dev stage until part or is taken in account
  hierarchical_clss:
    - cell_type_ontology_term_id
    #- tissue_ontology_term_id
    - disease_ontology_term_id
    #- development_stage_ontology_term_id
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
  clss_to_weight:
    - cell_type_ontology_term_id
    # - tissue_ontology_term_id
    - disease_ontology_term_id
    # - development_stage_ontology_term_id
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    # - cell_culture
  clss_to_pred: ${data.clss_to_weight}
  all_clss:
    - cell_type_ontology_term_id
    # - tissue_ontology_term_id
    - disease_ontology_term_id
    # - development_stage_ontology_term_id
    - assay_ontology_term_id
    - self_reported_ethnicity_ontology_term_id
    - sex_ontology_term_id
    - organism_ontology_term_id
    #- heat_diff
    #- total_counts
    #- nnz
    #- dpt_group
    #- dataset_id
    #- cell_culture
